-- webinar-chagim-claude: the two tables rung 1 reads and rung 4 writes.
-- Generated by `python ladder.py supabase` from data/customers.prepared.csv.
-- Applied once with psql (see scripts/supabase_setup.sh).

create table if not exists public.records (
  customer_id        text primary key,
  gender             text,
  senior_citizen     integer,
  partner            text,
  dependents         text,
  tenure             integer,
  phone_service      text,
  multiple_lines     text,
  internet_service   text,
  online_security    text,
  online_backup      text,
  device_protection  text,
  tech_support       text,
  streaming_tv       text,
  streaming_movies   text,
  contract           text,
  paperless_billing  text,
  payment_method     text,
  monthly_charges    numeric,
  total_charges      numeric,
  churn              text
);

-- RLS on, and an explicit read policy. With RLS on and no policy the API
-- returns zero rows and no error.
alter table public.records enable row level security;
drop policy if exists "public read" on public.records;
create policy "public read"   on public.records
  for select to anon using (true);

-- Rung 4's audit trail. The insert policy is deliberately open for the demo
-- and is said out loud on stage, not hidden.
create table if not exists public.predictions (
  id                 bigint generated always as identity primary key,
  record_id          text not null,
  probability        numeric,
  recommended_action text,
  model_version      text,
  created_at         timestamptz default now(),
  -- The loop. Empty on the day this is built, and that is the point: the
  -- prediction is written the moment it is made, the outcome only when reality
  -- arrives. Rung 8 measures the gap between the two.
  outcome            text,
  outcome_at         timestamptz
);

alter table public.predictions enable row level security;
drop policy if exists "public read"   on public.predictions;
drop policy if exists "public insert" on public.predictions;
drop policy if exists "public update" on public.predictions;
create policy "public read"   on public.predictions
  for select to anon using (true);
create policy "public insert" on public.predictions
  for insert to anon with check (true);
-- Writing the outcome back is an update, not an insert. Without this policy the
-- loop is a table nobody can ever close.
create policy "public update" on public.predictions
  for update to anon using (true) with check (true);

-- The loop. A person's verdict on one recommendation, and a better action.
create table if not exists public.feedback (
  id                 bigint generated always as identity primary key,
  prediction_id      bigint references public.predictions(id),
  record_id          text not null,
  probability        numeric,
  recommended_action text,
  verdict            text not null check (verdict in ('right', 'wrong')),
  actual_outcome     text,            -- 'stayed' (event did not happen) | 'left' | 'unknown'
  better_action      text,
  note               text,
  rules_version      integer,
  created_at         timestamptz default now()
);
alter table public.feedback enable row level security;
drop policy if exists "public read"   on public.feedback;
drop policy if exists "public insert" on public.feedback;
create policy "public read"   on public.feedback for select to anon using (true);
create policy "public insert" on public.feedback for insert to anon with check (true);

-- The bands the recommender reads, versioned. Version 1 is ladder.toml.
create table if not exists public.rules (
  id         bigint generated always as identity primary key,
  version    integer not null unique,
  bands      jsonb   not null,        -- [{"name","min","action"}], highest min first
  rationale  text,
  source     text not null,           -- 'seed' | 'learner:rules' | 'learner:groq' | 'chat:groq'
  evidence   jsonb,
  active     boolean not null default false,
  created_at timestamptz default now()
);
alter table public.rules enable row level security;
drop policy if exists "public read"   on public.rules;
drop policy if exists "public insert" on public.rules;
drop policy if exists "public update" on public.rules;
create policy "public read"   on public.rules for select to anon using (true);

insert into public.rules (version, bands, rationale, source, active)
select 1, '[{"name": "high", "min": 0.6, "action": "Contact this week and make a concrete offer"}, {"name": "medium", "min": 0.35, "action": "Add to next month''s outreach list"}, {"name": "low", "min": 0.0, "action": "No action"}]'::jsonb, 'The bands from ladder.toml.', 'seed', true
where not exists (select 1 from public.rules where version = 1);

-- The publish gate. One row, one column; RLS with no policy hides it from anon.
-- The value is written by supabase_setup.sh, never by this file.
create table if not exists public.publish_gate (token text primary key);
alter table public.publish_gate enable row level security;
revoke all on table public.publish_gate from anon;

create or replace function public.publish_rules(
  p_bands jsonb, p_source text, p_rationale text, p_evidence jsonb, p_token text
) returns integer
language plpgsql security definer set search_path = public
as $$
declare
  next_version integer;
  expected     text;
begin
  select token into expected from public.publish_gate limit 1;
  if expected is null or expected = '' or p_token is distinct from expected then
    raise exception 'publish refused: bad or missing token';
  end if;
  select coalesce(max(version), 0) + 1 into next_version from public.rules;
  update public.rules set active = false where active;
  insert into public.rules (version, bands, rationale, source, evidence, active)
  values (next_version, p_bands, p_rationale, p_source, coalesce(p_evidence, '{}'::jsonb), true);
  return next_version;
end;
$$;
revoke all on function public.publish_rules(jsonb, text, text, jsonb, text) from public;
grant execute on function public.publish_rules(jsonb, text, text, jsonb, text) to anon;
