"""The tables rung 1 reads and rung 4 writes, and the loop's two, generated from the data.

The records table's columns are whatever prepare produced, so the SQL is
written here rather than by hand. The predictions table never changes: it holds
an id, a probability, an action, a model version, a timestamp, and the two
columns that close the loop -- the outcome and when it arrived. That is true of
every dataset this skill will ever see.

Row level security is on for both tables, with an explicit read policy. With RLS
on and no policy the API returns zero rows and no error -- the single most
expensive trap in this whole stack, so the policy is generated, never optional.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd
from pandas.api import types as ptypes

from .context import LadderConfig

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "src"))

from insights import to_snake  # noqa: E402

RECORDS_TABLE = "records"
PREDICTIONS_TABLE = "predictions"
FEEDBACK_TABLE = "feedback"
RULES_TABLE = "rules"


def sql_type(series: pd.Series) -> str:
    if ptypes.is_integer_dtype(series):
        return "integer"
    if ptypes.is_float_dtype(series):
        return "numeric"
    if ptypes.is_bool_dtype(series):
        return "boolean"
    return "text"


def generate_schema(cfg: LadderConfig, df: pd.DataFrame) -> str:
    id_column = _id_column(cfg, df)
    width = max(len(c) for c in df.columns) + 2
    lines = []
    for column in df.columns:
        kind = sql_type(df[column])
        if column == id_column:
            kind += " primary key"
        lines.append(f"  {column.ljust(width)}{kind},")
    lines[-1] = lines[-1].rstrip(",")

    return f"""-- {cfg.name}: the two tables rung 1 reads and rung 4 writes.
-- Generated by `python ladder.py supabase` from data/{cfg.name}.csv.
-- Applied once with psql (see scripts/supabase_setup.sh).

create table if not exists public.{RECORDS_TABLE} (
{chr(10).join(lines)}
);

-- RLS on, and an explicit read policy. With RLS on and no policy the API
-- returns zero rows and no error.
alter table public.{RECORDS_TABLE} enable row level security;
drop policy if exists "public read" on public.{RECORDS_TABLE};
create policy "public read"   on public.{RECORDS_TABLE}
  for select to anon using (true);

-- Rung 4's audit trail. The insert policy is deliberately open for the demo
-- and is said out loud on stage, not hidden.
create table if not exists public.{PREDICTIONS_TABLE} (
  id                 bigint generated always as identity primary key,
  record_id          text not null,
  probability        numeric,
  recommended_action text,
  model_version      text,
  created_at         timestamptz default now(),
  -- The loop. Empty on the day this is built, and that is the point: the
  -- prediction is written the moment it is made, the outcome only when reality
  -- arrives. Rung 8 measures the gap between the two.
  outcome            text,
  outcome_at         timestamptz
);

alter table public.{PREDICTIONS_TABLE} enable row level security;
drop policy if exists "public read"   on public.{PREDICTIONS_TABLE};
drop policy if exists "public insert" on public.{PREDICTIONS_TABLE};
drop policy if exists "public update" on public.{PREDICTIONS_TABLE};
create policy "public read"   on public.{PREDICTIONS_TABLE}
  for select to anon using (true);
create policy "public insert" on public.{PREDICTIONS_TABLE}
  for insert to anon with check (true);
-- Writing the outcome back is an update, not an insert. Without this policy the
-- loop is a table nobody can ever close.
create policy "public update" on public.{PREDICTIONS_TABLE}
  for update to anon using (true) with check (true);
{loop_sql(cfg)}"""


def loop_sql(cfg: LadderConfig) -> str:
    """The loop: a verdict per recommendation, and versioned rules a second agent
    can rewrite. Anyone may read the rules and send a verdict -- that is the demo.
    Replacing the active rules goes through publish_rules(), which checks a token
    that supabase_setup.sh stores in publish_gate; the table itself refuses anon
    writes, so the app's buttons are not the only lock.
    """
    seed = json.dumps(
        [{"name": b.name, "min": b.minimum, "action": b.action} for b in cfg.bands],
        ensure_ascii=False,
    ).replace("'", "''")
    return f"""
-- The loop. A person's verdict on one recommendation, and a better action.
create table if not exists public.{FEEDBACK_TABLE} (
  id                 bigint generated always as identity primary key,
  prediction_id      bigint references public.{PREDICTIONS_TABLE}(id),
  record_id          text not null,
  probability        numeric,
  recommended_action text,
  verdict            text not null check (verdict in ('right', 'wrong')),
  actual_outcome     text,            -- 'stayed' (event did not happen) | 'left' | 'unknown'
  better_action      text,
  note               text,
  rules_version      integer,
  created_at         timestamptz default now()
);
alter table public.{FEEDBACK_TABLE} enable row level security;
drop policy if exists "public read"   on public.{FEEDBACK_TABLE};
drop policy if exists "public insert" on public.{FEEDBACK_TABLE};
create policy "public read"   on public.{FEEDBACK_TABLE} for select to anon using (true);
create policy "public insert" on public.{FEEDBACK_TABLE} for insert to anon with check (true);

-- The bands the recommender reads, versioned. Version 1 is ladder.toml.
create table if not exists public.{RULES_TABLE} (
  id         bigint generated always as identity primary key,
  version    integer not null unique,
  bands      jsonb   not null,        -- [{{"name","min","action"}}], highest min first
  rationale  text,
  source     text not null,           -- 'seed' | 'learner:rules' | 'learner:groq' | 'chat:groq'
  evidence   jsonb,
  active     boolean not null default false,
  created_at timestamptz default now()
);
alter table public.{RULES_TABLE} enable row level security;
drop policy if exists "public read"   on public.{RULES_TABLE};
drop policy if exists "public insert" on public.{RULES_TABLE};
drop policy if exists "public update" on public.{RULES_TABLE};
create policy "public read"   on public.{RULES_TABLE} for select to anon using (true);

insert into public.{RULES_TABLE} (version, bands, rationale, source, active)
select 1, '{seed}'::jsonb, 'The bands from ladder.toml.', 'seed', true
where not exists (select 1 from public.{RULES_TABLE} where version = 1);

-- The publish gate. One row, one column; RLS with no policy hides it from anon.
-- The value is written by supabase_setup.sh, never by this file.
create table if not exists public.publish_gate (token text primary key);
alter table public.publish_gate enable row level security;
revoke all on table public.publish_gate from anon;

create or replace function public.publish_rules(
  p_bands jsonb, p_source text, p_rationale text, p_evidence jsonb, p_token text
) returns integer
language plpgsql security definer set search_path = public
as $$
declare
  next_version integer;
  expected     text;
begin
  select token into expected from public.publish_gate limit 1;
  if expected is null or expected = '' or p_token is distinct from expected then
    raise exception 'publish refused: bad or missing token';
  end if;
  select coalesce(max(version), 0) + 1 into next_version from public.{RULES_TABLE};
  update public.{RULES_TABLE} set active = false where active;
  insert into public.{RULES_TABLE} (version, bands, rationale, source, evidence, active)
  values (next_version, p_bands, p_rationale, p_source, coalesce(p_evidence, '{{}}'::jsonb), true);
  return next_version;
end;
$$;
revoke all on function public.publish_rules(jsonb, text, text, jsonb, text) from public;
grant execute on function public.publish_rules(jsonb, text, text, jsonb, text) to anon;
"""


def write_schema(cfg: LadderConfig, df: pd.DataFrame) -> Path:
    path = cfg.root / "supabase" / "schema.sql"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(generate_schema(cfg, df), encoding="utf-8")
    return path


def _id_column(cfg: LadderConfig, df: pd.DataFrame) -> str:
    candidate = to_snake(cfg.id_column) if cfg.id_column else "row_id"
    return candidate if candidate in df.columns else df.columns[0]
